const books = [
  {
    id: 1,
    name: "Filosofi Teras",
    author: "Henry Manampiring",
    image: "https://covers.openlibrary.org/b/isbn/9786024125189-L.jpg",
    category: "Self Development",
    rating: { rate: 4.5, count: 120 },
    year: 2018,
    stock: 10,
    pages: 344,
    description: "Buku tentang filosofi stoa untuk kehidupan modern."
  },
  {
    id: 2,
    name: "Laskar Pelangi",
    author: "Andrea Hirata",
    image: "https://covers.openlibrary.org/b/isbn/9789793062792-L.jpg",
    category: "Novel",
    rating: { rate: 4.8, count: 500 },
    year: 2005,
    stock: 15,
    pages: 534,
    description: "Kisah perjuangan anak-anak Belitung meraih pendidikan."
  },
  {
    id: 3,
    name: "Bumi",
    author: "Tere Liye",
    image: "https://covers.openlibrary.org/b/isbn/9786020301129-L.jpg",
    category: "Fantasy",
    rating: { rate: 4.6, count: 300 },
    year: 2014,
    stock: 8,
    pages: 440,
    description: "Petualangan fantasi dunia paralel karya Tere Liye."
  },
  {
    id: 35,
    name: "Harry Potter and the Chamber of Secrets",
    category: "Fantasy",
    price: 130000,
    description: "Harry kembali ke Hogwarts untuk tahun keduanya, tapi sesuatu yang jahat mengintai di lorong-lorong sekolah. Suara misterius terdengar, pesan mengerikan muncul di dinding, dan murid-murid mulai membeku satu per satu...",
    author: "J.K. Rowling",
    publisher: "Bloomsbury",
    year: 1998,
    pages: 251,
    stock: 20,
    image: "https://covers.openlibrary.org/b/isbn/9780747538493-L.jpg",
    rating: { rate: 4.8, count: 980 }
  },
  {
    id: 36,
    name: "Percy Jackson and the Lightning Thief",
    category: "Fantasy",
    price: 118000,
    description: "Percy Jackson hampir dikeluarkan dari sekolah asrama lagi. Ternyata ia adalah seorang demigod, anak dari Poseidon, dan kini ia harus menghadapi para monster mitologi Yunani yang tiba-tiba nyata dalam hidupnya...",
    author: "Rick Riordan",
    publisher: "Disney Hyperion",
    year: 2005,
    pages: 377,
    stock: 22,
    image: "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg",
    rating: { rate: 4.7, count: 845 }
  },
  {
    id: 37,
    name: "1984",
    category: "Novel",
    price: 89000,
    description: "Di dunia yang dikuasai Big Brother, setiap gerak-gerik manusia diawasi dan setiap pikiran bisa jadi kejahatan. Winston Smith mulai mempertanyakan sistem yang selama ini ia patuhi tanpa syarat...",
    author: "George Orwell",
    publisher: "Secker & Warburg",
    year: 1949,
    pages: 328,
    stock: 14,
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    rating: { rate: 4.9, count: 760 }
  },
  {
    id: 1,
    name: "Laskar Pelangi",
    category: "Novel",
    price: 85000,
    description: "Di sebuah sekolah sederhana di Belitung, sepuluh anak dengan latar belakang berbeda dipertemukan oleh satu hal yang sama: mimpi untuk mendapatkan pendidikan yang lebih baik...",
    author: "Andrea Hirata",
    publisher: "Bentang Pustaka",
    year: 2005,
    pages: 529,
    stock: 18,
    image: "https://i.pinimg.com/736x/10/dc/06/10dc06814790d2159ade8a25ac61fa24.jpg",
    rating: { rate: 4.9, count: 328 }
  },
  {
    id: 2,
    name: "Bumi",
    category: "Fantasy",
    price: 95000,
    description: "Perjalanan hidup sering kali membawa seseorang ke tempat yang tidak pernah ia bayangkan sebelumnya...",
    author: "Tere Liye",
    publisher: "Gramedia Pustaka Utama",
    year: 2014,
    pages: 440,
    stock: 24,
    image: "https://i.pinimg.com/736x/e1/df/fc/e1dffcf4f2057935640e8a498dc61db9.jpg",
    rating: { rate: 4.8, count: 291 }
  },
  {
    id: 3,
    name: "Good Girl, Bad Blood",
    category: "Novel",
    price: 105000,
    description: "Ada kalanya seseorang harus berjalan jauh sebelum akhirnya memahami apa yang sebenarnya ia cari...",
    author: "Holly Jackson",
    publisher: "Electric Monkey",
    year: 2020,
    pages: 400,
    stock: 22,
    image: "https://i.pinimg.com/1200x/05/f2/13/05f213443837d372d20c2068e0f9afeb.jpg",
    rating: { rate: 4.8, count: 680 }
  },
  {
    id: 4,
    name: "Atomic Habits",
    category: "Self Development",
    price: 115000,
    description: "Tidak semua perjalanan dimulai karena seseorang sudah tahu ke mana ia akan pergi...",
    author: "James Clear",
    publisher: "Gramedia Pustaka Utama",
    year: 2019,
    pages: 320,
    stock: 30,
    image: "https://i.pinimg.com/736x/84/31/63/84316317e7f2919b153679e534eaffc5.jpg",
    rating: { rate: 4.9, count: 512 }
  },
  {
    id: 5,
    name: "Filosofi Teras",
    category: "Self Development",
    price: 89000,
    description: "Masa lalu tidak selalu benar-benar pergi meskipun waktu terus berjalan...",
    author: "Henry Manampiring",
    publisher: "Kompas",
    year: 2018,
    pages: 320,
    stock: 21,
    image: "https://i.pinimg.com/1200x/ee/20/d2/ee20d232056eca3d231720ef140a9485.jpg",
    rating: { rate: 4.8, count: 367 }
  },
  {
    id: 6,
    name: "The Psychology of Money",
    category: "Finance",
    price: 108000,
    description: "Hidup tidak selalu memberikan kesempatan kedua ketika seseorang melakukan kesalahan...",
    author: "Morgan Housel",
    publisher: "Harriman House",
    year: 2020,
    pages: 256,
    stock: 17,
    image: "https://i.pinimg.com/1200x/4e/f2/58/4ef258c122669970e4b43ef23fbc9dd6.jpg",
    rating: { rate: 4.9, count: 436 }
  },
  {
    id: 7,
    name: "Anonymous Crush",
    category: "Romance",
    price: 89000,
    description: "Di tengah kehidupan yang berjalan begitu cepat, terkadang seseorang berhenti dan bertanya...",
    author: "Salsabila Falensia",
    publisher: "Pastel Books",
    year: 2023,
    pages: 368,
    stock: 17,
    image: "https://i.ibb.co.com/DfC9qhSN/a8e8331def5a455dc82294cbb9e474f0.jpg",
    rating: { rate: 4.7, count: 185 }
  },
  {
    id: 8,
    name: "Perahu Kertas",
    category: "Romance",
    price: 87000,
    description: "Perjalanan ke tempat yang belum pernah dikenal selalu membawa kemungkinan...",
    author: "Dee Lestari",
    publisher: "Bentang Pustaka",
    year: 2009,
    pages: 444,
    stock: 19,
    image: "https://i.pinimg.com/736x/d6/f5/69/d6f56921b50cdcee8e625a0a3e91bd6f.jpg",
    rating: { rate: 4.7, count: 231 }
  },
  {
    id: 9,
    name: "Cantik Itu Luka",
    category: "Novel",
    price: 105000,
    description: "Ketika kehidupan mulai berubah, seseorang sering kali tidak memiliki pilihan selain belajar beradaptasi...",
    author: "Eka Kurniawan",
    publisher: "Gramedia Pustaka Utama",
    year: 2002,
    pages: 505,
    stock: 11,
    image: "https://i.pinimg.com/736x/b4/39/48/b439481027ddae82a1839bda635320b2.jpg",
    rating: { rate: 4.7, count: 198 }
  },
  {
    id: 10,
    name: "Sapiens",
    category: "Finance",
    price: 135000,
    description: "Ada banyak hal dalam hidup yang terlihat sederhana sampai seseorang harus memilih di antara dua pilihan...",
    author: "Yuval Noah Harari",
    publisher: "Harper",
    year: 2015,
    pages: 464,
    stock: 16,
    image: "https://i.pinimg.com/1200x/69/2b/80/692b807e2837f9645592276778672bef.jpg",
    rating: { rate: 4.9, count: 489 }
  },
  {
    id: 11,
    name: "Tentang Kamu",
    category: "Novel",
    price: 98000,
    description: "Sebuah perjalanan panjang tidak hanya mengubah tempat yang dituju, tetapi juga dapat mengubah seseorang...",
    author: "Tere Liye",
    publisher: "Republika",
    year: 2016,
    pages: 524,
    stock: 21,
    image: "https://i.pinimg.com/736x/00/ce/9f/00ce9f0bce4bac9e7cd53000dbe305d3.jpg",
    rating: { rate: 4.9, count: 423 }
  },
  {
    id: 12,
    name: "The Alpha Girl's Guide",
    category: "Self Development",
    price: 89000,
    description: "Kehidupan tokoh utama berubah ketika sebuah kejadian tidak terduga memaksanya meninggalkan rutinitas...",
    author: "Henry Manampiring",
    publisher: "GagasMedia",
    year: 2015,
    pages: 240,
    stock: 16,
    image: "https://i.pinimg.com/1200x/a0/16/43/a016436ecb0cac9371318b4b8045588b.jpg",
    rating: { rate: 4.8, count: 276 }
  },
  {
    id: 13,
    name: "The Alchemist",
    category: "Fantasy",
    price: 88000,
    description: "Sejak awal, tokoh utama selalu merasa ada bagian dari hidupnya yang belum benar-benar ia pahami...",
    author: "Paulo Coelho",
    publisher: "HarperCollins",
    year: 1988,
    pages: 208,
    stock: 14,
    image: "https://i.pinimg.com/1200x/49/7f/22/497f22527c6c0b20fb0bbe814ab918b2.jpg",
    rating: { rate: 4.9, count: 523 }
  },
  {
    id: 14,
    name: "The Midnight Library",
    category: "Fantasy",
    price: 102000,
    description: "Sebuah hubungan dapat dimulai dari pertemuan sederhana, tetapi tidak pernah ada yang tahu bagaimana akhirnya...",
    author: "Matt Haig",
    publisher: "Viking",
    year: 2020,
    pages: 304,
    stock: 20,
    image: "https://i.pinimg.com/1200x/4c/69/bb/4c69bb753cd665a9c366db62dca954de.jpg",
    rating: { rate: 4.8, count: 378 }
  },
  {
    id: 15,
    name: "Hujan",
    category: "Novel",
    price: 90000,
    description: "Sejak kecil, tokoh utama memiliki sebuah impian yang ingin diwujudkannya suatu hari nanti...",
    author: "Tere Liye",
    publisher: "Gramedia Pustaka Utama",
    year: 2016,
    pages: 318,
    stock: 18,
    image: "https://i.pinimg.com/736x/4a/e2/d8/4ae2d87de234aa6fb954edfe4eee42d9.jpg",
    rating: { rate: 4.8, count: 302 }
  },
  {
    id: 16,
    name: "Badan Intelijen Sekolah 2",
    category: "Novel",
    price: 99000,
    description: "Memasuki sebuah fase baru dalam kehidupan membuat tokoh utama mulai menyadari...",
    author: "Intanzs",
    publisher: "Butterflies Books",
    year: 2025,
    pages: 320,
    stock: 20,
    image: "https://i.ibb.co.com/DDQGM18B/df861db9cbe54e788929c56e7c29fdac.jpg",
    rating: { rate: 4.8, count: 320 }
  },
  {
    id: 17,
    name: "Laut Bercerita",
    category: "Novel",
    price: 105000,
    description: "Masa lalu selalu memiliki cara untuk kembali hadir, bahkan ketika seseorang berusaha meninggalkannya...",
    author: "Leila S. Chudori",
    publisher: "Kepustakaan Populer Gramedia",
    year: 2017,
    pages: 379,
    stock: 12,
    image: "https://i.pinimg.com/736x/9a/bb/61/9abb61fcf68afd124375a82dfd02ca6a.jpg",
    rating: { rate: 4.9, count: 467 }
  },
  {
    id: 18,
    name: "Home Sweet Loan",
    category: "Romance",
    price: 98000,
    description: "Tidak semua orang mendapatkan kesempatan untuk memulai hidup dari awal...",
    author: "Almira Bastari",
    publisher: "Gramedia Pustaka Utama",
    year: 2022,
    pages: 312,
    stock: 16,
    image: "https://i.pinimg.com/736x/50/24/5b/50245beedfccd8ffb26f378a3e09c258.jpg",
    rating: { rate: 4.8, count: 246 }
  },
  {
    id: 19,
    name: "Atomic Focus",
    category: "Self Development",
    price: 92000,
    description: "Sebuah kejadian sederhana membawa tokoh utama pada sebuah perjalanan yang sama sekali tidak direncanakan...",
    author: "Chris Bailey",
    publisher: "Vermilion",
    year: 2022,
    pages: 256,
    stock: 23,
    image: "https://i.pinimg.com/236x/ec/ed/71/eced713af1021bab77a0fa54fd9cde95.jpg",
    rating: { rate: 4.6, count: 173 }
  },
  {
    id: 20,
    name: "Berandal Bandung",
    category: "Novel",
    price: 95000,
    description: "Setiap orang memiliki impian yang ingin dicapai, tetapi tidak semua orang memiliki keberanian...",
    author: "Wulan Nur Amalia",
    publisher: "Black Swan Books",
    year: 2024,
    pages: 320,
    stock: 17,
    image: "https://i.ibb.co.com/zWHPXg4f/3b030543d57df3c321146378aa1154bb.jpg",
    rating: { rate: 4.8, count: 245 }
  },
  {
    id: 21,
    name: "Rumah untuk Alie",
    category: "Novel",
    price: 95000,
    description: "Kehidupan yang selama ini terasa biasa tiba-tiba berubah setelah sebuah peristiwa...",
    author: "Luluk HF",
    publisher: "Mediakita",
    year: 2024,
    pages: 352,
    stock: 18,
    image: "https://i.pinimg.com/736x/3e/80/62/3e8062e662cc8c45f1e132c42d52c5c7.jpg",
    rating: { rate: 4.8, count: 280 }
  },
  {
    id: 22,
    name: "Pulang Pergi",
    category: "Novel",
    price: 105000,
    description: "Di balik kehidupan yang terlihat sempurna, selalu ada cerita yang tidak diketahui orang lain...",
    author: "Tere Liye",
    publisher: "Sabak Grip",
    year: 2021,
    pages: 414,
    stock: 17,
    image: "https://i.pinimg.com/736x/c3/a1/9d/c3a19d0a7e2a5d221f25f4ff7ba5e49a.jpg",
    rating: { rate: 4.8, count: 267 }
  },
  {
    id: 23,
    name: "Think Again",
    category: "Self Development",
    price: 118000,
    description: "Sebuah kota menyimpan begitu banyak cerita dari orang-orang yang datang dan pergi...",
    author: "Adam Grant",
    publisher: "Viking",
    year: 2021,
    pages: 320,
    stock: 19,
    image: "https://i.pinimg.com/736x/fd/0c/8e/fd0c8eab7a41663dea3d69add32fa3b4.jpg",
    rating: { rate: 4.7, count: 298 }
  },
  {
    id: 24,
    name: "The Magic Library",
    category: "Fantasy",
    price: 98000,
    description: "Tokoh utama selalu percaya bahwa hidup dapat direncanakan dengan baik...",
    author: "J. L. Black",
    publisher: "Magic Library Press",
    year: 2023,
    pages: 280,
    stock: 16,
    image: "https://i.pinimg.com/1200x/e9/b6/35/e9b635c9ae587383377aaa458682084d.jpg",
    rating: { rate: 4.7, count: 210 }
  },
  {
    id: 25,
    name: "No More Burnout",
    category: "Self Development",
    price: 95000,
    description: "Di tengah kehidupan yang semakin dipenuhi tuntutan, tekanan, dan kesibukan...",
    author: "A. P. Rao",
    publisher: "Penguin Books",
    year: 2023,
    pages: 332,
    stock: 18,
    image: "https://i.ibb.co.com/jPHy0cZq/b380c8e039d637f7befdac069ebd2f25.jpg",
    rating: { rate: 4.7, count: 195 }
  },
  {
    id: 26,
    name: "Dilan 1990",
    category: "Romance",
    price: 82000,
    description: "Bandung tahun 1990 menjadi awal dari sebuah kisah yang tidak pernah dibayangkan Milea sebelumnya...",
    author: "Pidi Baiq",
    publisher: "Pastel Books",
    year: 2014,
    pages: 408,
    stock: 20,
    image: "https://i.pinimg.com/1200x/8f/82/ba/8f82ba34241d0620c96e2b9eb0f66eef.jpg",
    rating: { rate: 4.7, count: 342 }
  },
  {
    id: 27,
    name: "Ronggeng Dukuh Paruk",
    category: "Novel",
    price: 97000,
    description: "Di sebuah dusun kecil bernama Dukuh Paruk, kehidupan masyarakat berjalan mengikuti tradisi...",
    author: "Ahmad Tohari",
    publisher: "Gramedia Pustaka Utama",
    year: 1982,
    pages: 236,
    stock: 9,
    image: "https://i.pinimg.com/736x/c6/11/0d/c6110df93fe1e6a2013e8a2221cd3e43.jpg",
    rating: { rate: 4.8, count: 218 }
  },
  {
    id: 28,
    name: "The Power of Now",
    category: "Self Development",
    price: 112000,
    description: "Banyak orang menghabiskan hidup dengan memikirkan masa lalu atau mencemaskan masa depan...",
    author: "Eckhart Tolle",
    publisher: "New World Library",
    year: 1997,
    pages: 236,
    stock: 14,
    image: "https://i.pinimg.com/236x/e6/85/62/e68562bd294d714ff3c100cc1922b75a.jpg",
    rating: { rate: 4.8, count: 365 }
  },
  {
    id: 29,
    name: "The Little Prince",
    category: "Fantasy",
    price: 78000,
    description: "Seorang pilot terdampar di tengah gurun setelah pesawatnya mengalami masalah...",
    author: "Antoine de Saint-Exupéry",
    publisher: "Gallimard",
    year: 1943,
    pages: 96,
    stock: 32,
    image: "https://i.pinimg.com/736x/20/c8/4b/20c84b4c7b0a238c94e24e7c3720d7c5.jpg",
    rating: { rate: 4.9, count: 521 }
  },
  {
    id: 30,
    name: "Harry Potter and the Philosopher's Stone",
    category: "Fantasy",
    price: 125000,
    description: "Harry Potter tumbuh sebagai seorang anak yatim yang tinggal bersama keluarga Dursley...",
    author: "J.K. Rowling",
    publisher: "Bloomsbury",
    year: 1997,
    pages: 309,
    stock: 25,
    image: "https://i.pinimg.com/1200x/10/36/03/103603cfb9681d280af6cef1de9cb7bb.jpg",
    rating: { rate: 4.9, count: 1250 }
  },
  {
    id: 31,
    name: "Malioboro at Midnight",
    category: "Romance",
    price: 99000,
    description: "Serana Nighita mencoba menjalani kehidupannya setelah berbagai hal tidak berjalan sesuai harapan...",
    author: "Skysphire",
    publisher: "Bukune Kreatif Cipta",
    year: 2023,
    pages: 320,
    stock: 20,
    image: "https://i.pinimg.com/736x/ba/be/97/babe975c886039104d1dcdae3bd79287.jpg",
    rating: { rate: 4.8, count: 356 }
  },
  {
    id: 32,
    name: "Bandung After Rain",
    category: "Romance",
    price: 95000,
    description: "Bandung menyimpan banyak kenangan bagi Hema dan Ra, termasuk cerita yang pernah mereka jalani...",
    author: "Wulan Nur Amalia",
    publisher: "Black Swan Books",
    year: 2024,
    pages: 320,
    stock: 18,
    image: "https://i.ibb.co.com/tPcZRynz/6926dd3c775fe7d0f852f68cb9819390.jpg",
    rating: { rate: 4.9, count: 287 }
  },
  {
    id: 33,
    name: "The Intelligent Investor",
    category: "Finance",
    price: 125000,
    description: "Dunia investasi sering kali terlihat menarik karena menjanjikan peluang untuk mendapatkan keuntungan...",
    author: "Benjamin Graham",
    publisher: "HarperBusiness",
    year: 1949,
    pages: 640,
    stock: 15,
    image: "https://i.pinimg.com/736x/20/06/4e/20064ec997cf77cbff970890a3c75bc7.jpg",
    rating: { rate: 4.8, count: 425 }
  },
  {
    id: 34,
    name: "Think and Grow Rich",
    category: "Finance",
    price: 95000,
    description: "Kesuksesan sering kali dimulai dari sebuah tujuan yang jelas dan keyakinan untuk terus mengejarnya...",
    author: "Napoleon Hill",
    publisher: "The Ralston Society",
    year: 1937,
    pages: 238,
    stock: 22,
    image: "https://i.pinimg.com/736x/29/cb/09/29cb093a75c57356a8efa8f567dd529b.jpg",
    rating: { rate: 4.7, count: 510 }
  },
  {
    id: 35,
    name: "Harry Potter and the Chamber of Secrets",
    category: "Fantasy",
    price: 130000,
    description: "Harry kembali ke Hogwarts untuk tahun keduanya, tapi sesuatu yang jahat mengintai di lorong-lorong sekolah. Suara misterius terdengar, pesan mengerikan muncul di dinding, dan murid-murid mulai membeku satu per satu...",
    author: "J.K. Rowling",
    publisher: "Bloomsbury",
    year: 1998,
    pages: 251,
    stock: 20,
    image: "https://covers.openlibrary.org/b/isbn/9780747538493-L.jpg",
    rating: { rate: 4.8, count: 980 }
  },
  {
    id: 36,
    name: "Percy Jackson and the Lightning Thief",
    category: "Fantasy",
    price: 118000,
    description: "Percy Jackson hampir dikeluarkan dari sekolah asrama lagi. Ternyata ia adalah seorang demigod, anak dari Poseidon, dan kini ia harus menghadapi para monster mitologi Yunani yang tiba-tiba nyata dalam hidupnya...",
    author: "Rick Riordan",
    publisher: "Disney Hyperion",
    year: 2005,
    pages: 377,
    stock: 22,
    image: "https://covers.openlibrary.org/b/isbn/9780786838653-L.jpg",
    rating: { rate: 4.7, count: 845 }
  },
  {
    id: 37,
    name: "1984",
    category: "Novel",
    price: 89000,
    description: "Di dunia yang dikuasai Big Brother, setiap gerak-gerik manusia diawasi dan setiap pikiran bisa jadi kejahatan. Winston Smith mulai mempertanyakan sistem yang selama ini ia patuhi tanpa syarat...",
    author: "George Orwell",
    publisher: "Secker & Warburg",
    year: 1949,
    pages: 328,
    stock: 14,
    image: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    rating: { rate: 4.9, count: 760 }
  }
];